# Generated by Django 5.2.7 on 2025-10-26 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="id",
            new_name="isbn",
        ),
    ]
