# Generated by Django 5.2.7 on 2025-10-29 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_id_post_isbn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(error_messages={'required': 'author field is required'}, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(error_messages={'blank': 'content field cannot be empty', 'required': 'content field is required'}),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'blank': 'title field cannot be empty', 'max_length': 'cannot accept more than 50 characters', 'required': 'title field is required'}, max_length=50),
        ),
    ]
