# Generated by Django 5.2.7 on 2025-12-20 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="isbn", new_name="id"),
    ]
