# Generated by Django 5.2.7 on 2025-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(error_messages={'blank': 'content field cannot be empty'}),
        ),
    ]
